name: guam_community_client
description: We connect developers.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.3
  modal_bottom_sheet: ^2.0.0
  conditional_builder: ^1.0.2
  flutter_form_builder: ^6.0.0-nullsafety.1
  intl: ^0.17.0
  bot_toast: ^4.0.1
  dotted_border: ^2.0.0+1
  url_launcher: ^6.0.5
  flutter_secure_storage: ^5.0.2
  flutter_portal: ^0.4.0
  flutter_mentions: 2.0.1
  jiffy: ^5.0.0
  flutter_linkify: ^5.0.2
  path_provider: ^2.0.9

  # Image
  flutter_svg: ^0.23.0+1
  transparent_image: ^2.0.0
  image_picker: ^0.7.4
  carousel_slider: ^4.0.0

  # FlutterFire
  firebase_core: ^1.12.0
  firebase_analytics: ^9.1.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  firebase_messaging: ^11.2.6

  # Kakao Login Dependency
  kakao_flutter_sdk: ^0.9.0
  dio: ^4.0.4
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.13
  platform: ^3.1.0
  package_info: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/gifs/
    - assets/backgrounds/
    - assets/backgrounds/splash/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SpoqaHanSansNeoMedium
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Medium.ttf
          weight: 400
    - family: SpoqaHanSansNeoRegular
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
